// Core story player component.
// Plays slide audio via expo-av and highlights each word in sync with the audio
// using word_timestamps from the DB (generated by Google TTS SSML marks, ADR 005).

import { useEffect, useRef, useState, useCallback } from 'react'
import { View, Text, Pressable, ActivityIndicator, StyleSheet } from 'react-native'
import { Audio } from 'expo-av'
import * as Haptics from 'expo-haptics'
import { getAudioUri } from '@/lib/audio'
import type { LanguageCode } from '@/lib/i18n'

interface WordTimestamp {
  word: string
  start_ms: number
  end_ms: number
}

interface Props {
  storyId: string
  slideId: string
  text: string
  audioUrl: string | undefined
  wordTimestamps: WordTimestamp[]
  lang: LanguageCode
  onSlideComplete: () => void
}

type PlayerState = 'idle' | 'loading' | 'playing' | 'paused' | 'done'

export default function AudioPlayer({
  storyId, slideId, text, audioUrl, wordTimestamps, lang, onSlideComplete,
}: Props) {
  const soundRef = useRef<Audio.Sound | null>(null)
  const [playerState, setPlayerState] = useState<PlayerState>('idle')
  const [positionMs, setPositionMs] = useState(0)
  const [durationMs, setDurationMs] = useState(0)

  // Find the word index active at the current playback position
  const activeWordIndex = wordTimestamps.findIndex(
    (wt, i) =>
      positionMs >= wt.start_ms &&
      (wordTimestamps[i + 1] ? positionMs < wordTimestamps[i + 1].start_ms : true),
  )

  // Split text into words matching the timestamps array order
  const words = text.trim().split(/\s+/).filter(Boolean)

  const unloadSound = useCallback(async () => {
    if (soundRef.current) {
      await soundRef.current.unloadAsync().catch(() => {})
      soundRef.current = null
    }
  }, [])

  // Reload when slide changes
  useEffect(() => {
    setPlayerState('idle')
    setPositionMs(0)
    return () => { unloadSound() }
  }, [slideId, unloadSound])

  async function play() {
    if (!audioUrl) return
    setPlayerState('loading')

    await Audio.setAudioModeAsync({ playsInSilentModeIOS: true })

    // Get cached local URI or download (ADR 013)
    const uri = await getAudioUri(audioUrl, storyId, slideId, lang).catch(() => audioUrl)

    const { sound } = await Audio.Sound.createAsync(
      { uri },
      { shouldPlay: true },
      (status) => {
        if (!status.isLoaded) return
        setPositionMs(status.positionMillis)
        setDurationMs(status.durationMillis ?? 0)
        if (status.didJustFinish) {
          setPlayerState('done')
          Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light)
          onSlideComplete()
        }
      },
    )

    soundRef.current = sound
    setPlayerState('playing')
  }

  async function togglePause() {
    if (!soundRef.current) return
    if (playerState === 'playing') {
      await soundRef.current.pauseAsync()
      setPlayerState('paused')
    } else {
      await soundRef.current.playAsync()
      setPlayerState('playing')
    }
  }

  const progressPercent = durationMs > 0 ? (positionMs / durationMs) * 100 : 0

  return (
    <View style={styles.container}>
      {/* Highlighted text */}
      <Text style={styles.slideText}>
        {words.map((word, i) => (
          <Text
            key={i}
            style={[
              styles.word,
              i === activeWordIndex && playerState === 'playing' && styles.activeWord,
            ]}
          >
            {word}{' '}
          </Text>
        ))}
      </Text>

      {/* Progress bar */}
      {durationMs > 0 && (
        <View style={styles.progressTrack}>
          <View style={[styles.progressFill, { width: `${progressPercent}%` }]} />
        </View>
      )}

      {/* Play / pause control */}
      <View style={styles.controls}>
        {playerState === 'loading' ? (
          <ActivityIndicator color="#FF6B00" />
        ) : playerState === 'idle' || playerState === 'done' ? (
          <Pressable
            onPress={play}
            style={({ pressed }) => [styles.playBtn, pressed && styles.pressed]}
          >
            <Text style={styles.playIcon}>{playerState === 'done' ? '↩' : '▶'}</Text>
          </Pressable>
        ) : (
          <Pressable
            onPress={togglePause}
            style={({ pressed }) => [styles.playBtn, pressed && styles.pressed]}
          >
            <Text style={styles.playIcon}>{playerState === 'playing' ? '⏸' : '▶'}</Text>
          </Pressable>
        )}

        {!audioUrl && (
          <Text style={styles.noAudio}>Audio not yet generated for this language</Text>
        )}
      </View>
    </View>
  )
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  slideText: {
    fontSize: 22,
    lineHeight: 38,
    color: '#1a1a1a',
    textAlign: 'center',
    flexWrap: 'wrap',
    paddingHorizontal: 8,
  },
  word: { color: '#1a1a1a' },
  activeWord: {
    color: '#FF6B00',
    fontWeight: '700',
    // React Native doesn't support background on inline Text, so we use colour only
  },
  progressTrack: {
    height: 3,
    backgroundColor: '#f0f0f0',
    borderRadius: 2,
    marginVertical: 20,
    overflow: 'hidden',
  },
  progressFill: { height: '100%', backgroundColor: '#FF6B00', borderRadius: 2 },
  controls: { alignItems: 'center', marginTop: 8 },
  playBtn: {
    width: 64, height: 64, borderRadius: 32,
    backgroundColor: '#FF6B00',
    alignItems: 'center', justifyContent: 'center',
    shadowColor: '#FF6B00', shadowOpacity: 0.4, shadowRadius: 12, elevation: 6,
  },
  pressed: { opacity: 0.85, transform: [{ scale: 0.96 }] },
  playIcon: { fontSize: 24, color: '#fff' },
  noAudio: { marginTop: 12, fontSize: 12, color: '#aaa', textAlign: 'center' },
})
